---
apiVersion: policies.kubewarden.io/v1alpha2
kind: ClusterAdmissionPolicy
metadata:
  name: pod-runtime-lockc-runc-wrapper
spec:
  module: registry://ghcr.io/kubewarden/policies/pod-runtime:v0.1.3
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
    operations:
    - CREATE
    - UPDATE
  mutating: true
  settings:
    reservedRuntimes:
    - runC
    fallbackRuntime: lockc-runc-wrapper
    defaultRuntimeReserved: true
