apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lockc-agent
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "watch", "list"]
